include:
  - ./proxy.yaml

services:
  web:
    build: ./Dockerfile.python
    image: cr.yandex/crp6jqsj0i4sre27dpem/app:0.0.1
    restart: always
    environment:
      - DB_HOST=db
      - DB_USER=app
      - DB_PASSWORD=QwErTy1234
      - DB_NAME=virtd
    depends_on:
      - db
    networks:
      backend:
        ipv4_address: 172.20.0.5

  db:
    image: mysql:8
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      backend:
        ipv4_address: 172.20.0.10
    env_file:
      - .env
