include:
  - ./proxy.yaml

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.python
      tags:
        - cr.yandex/crp6jqsj0i4sre27dpem/app:0.0.1
    restart: always
    environment:
      - DB_HOST=db
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
    env_file:
      - .env
    depends_on:
      - db
    networks:
      backend:
        ipv4_address: 172.20.0.5

  db:
    image: mysql:8
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s
    environment:
      - MYSQL_DEFAULT_AUTHENTICATION_PLUGIN=caching_sha2_password
    networks:
      backend:
        ipv4_address: 172.20.0.10
    env_file:
      - .env
